CREATE TABLE energy_analysis (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumo_kwh               DECIMAL(10,2) NOT NULL,
    uso_horario_pico          BOOLEAN NOT NULL,
    quantidade_equipamentos   INT NOT NULL,
    tipo_imovel               VARCHAR(50) NOT NULL,
    horas_alto_consumo        INT NOT NULL,
    categoria                 VARCHAR(50) NOT NULL,
    probabilidade             DECIMAL(5,2) NOT NULL,
    score                     INT NOT NULL,
    custo_estimado_mensal     DECIMAL(10,2) NOT NULL,
    fonte_classificacao       VARCHAR(50) NOT NULL,
    recomendacoes             CLOB NOT NULL,
    created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_tipo_imovel CHECK (tipo_imovel IN ('CASA','APARTAMENTO','COMERCIO','ESCRITORIO','INDUSTRIA','OUTRO')),
    CONSTRAINT chk_categoria CHECK (categoria IN ('EFICIENTE','MODERADO','INEFICIENTE')),
    CONSTRAINT chk_fonte_classificacao CHECK (fonte_classificacao IN ('RULE_BASED','ML_MODEL','RULE_BASED_FALLBACK'))
);
