CREATE TABLE app_user (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(255) NOT NULL,
    email         VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role          VARCHAR2(50)  NOT NULL,
    active        NUMBER(1)     NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT uk_app_user_email
        UNIQUE (email),

    CONSTRAINT chk_app_user_active
        CHECK (active IN (0, 1)),

    CONSTRAINT chk_app_user_role
        CHECK (role IN ('USER'))
);
