CREATE TABLE refresh_token (
    id                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER(19) NOT NULL,
    token_hash           VARCHAR2(64) NOT NULL,
    family_id            VARCHAR2(36) NOT NULL,
    expires_at           TIMESTAMP NOT NULL,
    family_expires_at    TIMESTAMP NOT NULL,
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked_at           TIMESTAMP NULL,
    replaced_by_token_id NUMBER(19) NULL,
    revocation_reason    VARCHAR2(32) NULL,

    CONSTRAINT uk_refresh_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(id),

    CONSTRAINT fk_refresh_token_replaced
        FOREIGN KEY (replaced_by_token_id)
        REFERENCES refresh_token(id),

    CONSTRAINT uk_refresh_token_replaced
        UNIQUE (replaced_by_token_id),

    CONSTRAINT chk_refresh_token_reason
        CHECK (
            revocation_reason IS NULL OR
            revocation_reason IN (
                'ROTATED',
                'LOGOUT',
                'REUSE_DETECTED',
                'USER_INACTIVE',
                'FAMILY_EXPIRED'
            )
        )
);

CREATE INDEX idx_refresh_token_user_id
    ON refresh_token(user_id);

CREATE INDEX idx_refresh_token_family_id
    ON refresh_token(family_id);

CREATE INDEX idx_refresh_token_expires_at
    ON refresh_token(expires_at);
