spring.application.name=energiai
server.servlet.context-path=/api/v1
spring.web.error.include-stacktrace=NEVER
energy.tariff.default=0.75
cors.allowed-origins=http://localhost:3000,http://localhost:5173

# remover caso o flyway estiver pronto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
