spring.application.name=backend

# Porta padrao
server.port=8080

# Contexto da aplicacao (prefixo da URL)
server.servlet.context-path=/energiai

# Datasource H2 (para ambiente local)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configurações de Negócio
energy.tariff.default=0.75
